discord_token: "YOUR_DISCORD_TOKEN"
server_name: "server name"

chat:
  enabled: true
  channel: 997551922800246886
  send_from_discord: true
  messages:
    join: true
    leave: true
    chat: true
    advancement: true
    death: true
    server: true

music:
  enabled: true
  channel: 997551922800246886
  bot_prefix: "$"

commands:
  other:
    uwu:
      enabled: true
    hello:
      enabled: true
